// export const ACTION_SET_REPORTS = 'reports/ACTION_SET_REPORTS'
export const ACTION_SET_QUESTIONS = 'questions/ACTION_SET_QUESTIONS'
export const ACTION_ADD_QUESTION = 'questions/ACTION_ADD_QUESTION'
export const ACTION_DELETE_QUESTION = 'questions/ACTION_DELETE_QUESTION'
export const ACTION_UPDATE_QUESTION = 'questions/ACTION_UPDATE_QUESTION'

export const MUTATION_SET_QUESTIONS = 'questions/MUTATION_SET_QUESTIONS'
export const MUTATION_ADD_QUESTION = 'questions/MUTATION_ADD_QUESTION'
export const MUTATION_DELETE_QUESTION = 'questions/MUTATION_DELETE_QUESTION'
export const MUTATION_UPDATE_QUESTION = 'questions/MUTATION_UPDATE_QUESTION'

export const GETTER_QUESTION = 'questions/GETTER_QUESTION'
