// export const ACTION_SET_REPORTS = 'reports/ACTION_SET_REPORTS'
export const ACTION_SET_QUESTIONNAIRE = 'questions/ACTION_SET_QUESTIONNAIRE'
export const ACTION_ADD_QUESTIONNAIRE = 'questions/ACTION_ADD_QUESTIONNAIRE'
export const ACTION_DELETE_QUESTIONNAIRE = 'questions/ACTION_DELETE_QUESTIONNAIRE'
export const ACTION_UPDATE_QUESTIONNAIRE = 'questions/ACTION_UPDATE_QUESTIONNAIRE'

export const MUTATION_SET_QUESTIONNAIRE = 'questions/MUTATION_SET_QUESTIONNAIRE'
export const MUTATION_ADD_QUESTIONNAIRE = 'questions/MUTATION_ADD_QUESTIONNAIRE'
export const MUTATION_DELETE_QUESTIONNAIRE = 'questions/MUTATION_DELETE_QUESTIONNAIRE'
export const MUTATION_UPDATE_QUESTIONNAIRE = 'questions/MUTATION_UPDATE_QUESTIONNAIRE'

export const GETTER_QUESTIONNAIRE = 'questions/GETTER_QUESTIONNAIRE'
